### ISSUE TITLE
Data cleanup from import automation incorrectly handles Multiples (data_object_type Metagenome HQMQ Bins Compression File)

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc_automation#440]
In testing some JAMO records for ingest we found that nmdc:wfmag-12-dtmz2z40.1 has a bunch of duplicate has_output values:
https://api.microbiomedata.org/nmdcschema/ids/nmdc%3Awfmag-12-dtmz2z40.1

```
 "has_output": [
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45",
    "nmdc:dobj-12-89dk2x45"
  ],
```

There is only a single zip file in the directory, so I these all map to that, but wanted to bring this to your attention in case there is an issue in the automation code. 

The mongo records will also need to be cleaned up

**Comment by kaijli** [comment]
Everything from 
```
{
    version: 'v1.3.12',
    type: 'nmdc:MagsAnalysis',
    execution_resource: 'JGI'
  }
```
Has repetitive output values. Need to change the data objects and clean them up.

**Comment by kaijli** [comment]
Checking through the output file of `nmdc:wfmag-11-bymmns29.1`, which is one of the many IDs pulled from the above query. The DataObject is a "Metagenome HQMQ Bins Compression File" available via [URL]( https://data.microbiomedata.org/data/nmdc:omprc-11-0011q207/nmdc:wfmag-11-bymmns29.1/nmdc_wfmag-11-bymmns29.1_hqmq_bin.zip). Unzipped two layers in and the file tree is as follows:
```
nmdc_wfmag-11-bymmns29.1_hqmq_bin
  3300053125_7.tar.gz
  3300053125_9.tar.gz
  3300053125_11.tar.gz
  3300053125_12.tar.gz
  3300053125_13.tar.gz
  3300053125_16/
    3300053125_16.cog.txt
    3300053125_16.ec.txt
    3300053125_16.faa
    3300053125_16.fna
    3300053125_16.gene_product.txt
    3300053125_16.gff
    3300053125_16.ko.txt
    3300053125_16.pfam.txt
    3300053125_16.phylodist.txt
    3300053125_16.tigr.txt
    mbin_datafile_3300053125.txt
    README
```
The expected imports from JGI MAGs runs are as follows from the [import.yaml](https://github.com/microbiomedata/nmdc_automation/blob/8900c84b7a210f3b2a6972caf58599d092e1ecf1/configs/import.yaml#L151C1-L155C32):
```
    Outputs:
      - CheckM Statistics
      - Metagenome Bins
      - GTDBTK Bacterial Summary
      - GTDBTK Archaeal Summary
Unique: 
    - data_object_type: CheckM Statistics
      description: CheckM for {id}
      name: CheckM statistics report
      import_suffix: _checkm_qa\.out$
      nmdc_suffix: _checkm_qa.out
      input_to: []
      output_of:  nmdc:MagsAnalysis
      multiple: false
      action: rename
    - data_object_type: GTDBTK Bacterial Summary
      description: Bacterial Summary for {id}
      name: GTDBTK bacterial summary
      import_suffix: _gtdbtk\.bac122\.summary\.tsv$
      nmdc_suffix: _gtdbtk.bac122.summary.tsv
      input_to: []
      output_of:  nmdc:MagsAnalysis
      multiple: false
      action: rename
    - data_object_type: GTDBTK Archaeal Summary
      description: Archaeal Summary for {id}
      name: GTDBTK archaeal summary
      import_suffix: _gtdbtk\.ar122\.summary\.tsv$
      nmdc_suffix: _gtdbtk.ar122.summary.tsv
      input_to: []
      output_of:  nmdc:MagsAnalysis
      multiple: false
      action: rename
  Multiples:
    - data_object_type: Metagenome HQMQ Bins Compression File
      description: Metagenome Bins for {id}
      name: Metagenome bin tarfiles archive
      import_suffix: _[0-9]+\.tar\.gz$
      nmdc_suffix: _hqmq_bin.zip
      input_to: []
      output_of:  nmdc:MagsAnalysis
      multiple: true
      action: zip
```
To trace back to where these files were imported from, `nmdc:omprc-11-0011q207` pointed to `gold_sequencing_project_identifiers: "gold:Gp0587799"` in nmdc.data_generation_set. Searching "Gp0587799" on the [GOLD site](https://gold.jgi.doe.gov/project?id=Gp0587799) allowed me to find the [Ga0500618 ID linked](https://gold.jgi.doe.gov/analysis_projects?id=Ga0500618) at the bottom of the page. I know there's some aggregations I can do instead of the following, but the next steps were faster than finding the commands. Found the directory for the analysis project at `/global/cfs/cdirs/m3408/aim2/dev/bioscales_mapping/bioscales_analysis_projects/Ga0500618/`
Looking through the directory, I was unable to find any of the other output types except for the bins:
```
> ls | grep .tar.gz
3300053125_11.tar.gz
3300053125_12.tar.gz
3300053125_13.tar.gz
3300053125_16.tar.gz
3300053125_7.tar.gz
3300053125_9.tar.gz
3300053125.tar.gz           # excluded via the regex because we manually zip the above anyway
```
which matches what is in `nmdc_wfmag-11-bymmns29.1_hqmq_bin.zip`. 

Therefore, the question is whether the other files are fully expected and whether a readme or info file is expected outside of the one included within the zipped file. 
Next steps for removing all instances except one as outputs for the 268 records that were imported in this batch of issues. 

cc: @aclum
